# Generated by Django 5.2.4 on 2026-07-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('target_math', models.PositiveSmallIntegerField(default=80)),
                ('target_english', models.PositiveSmallIntegerField(default=80)),
                ('target_iq', models.PositiveSmallIntegerField(default=80)),
                ('target_ielts', models.DecimalField(decimal_places=1, default=6.5, max_digits=3)),
                ('target_sat', models.PositiveSmallIntegerField(default=1400)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('ielts', 'IELTS'), ('sat', 'SAT'), ('cefr', 'CEFR'), ('other', 'Boshqa')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_year', models.PositiveSmallIntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_university_goals', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='university_goal', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_goals', to='pathways.university')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
