# Generated by Django 5.2.4 on 2026-07-18 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_exams', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='accounts.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.exam')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Topshirildi'), ('expired', 'Vaqt tugadi')], db_index=True, default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_ready', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='diagnostics.examassignment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('range_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('range_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('readiness', models.CharField(choices=[('ready', 'Tayyor'), ('not_ready', 'Tayyor emas')], max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics.examattempt')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_score', models.PositiveSmallIntegerField(default=85)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Tasdiqlangan'), ('active', 'Faol'), ('completed', 'Yakunlangan')], default='draft', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='diagnostics.diagnosticreport')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('start_month', models.PositiveSmallIntegerField(default=0)),
                ('end_month', models.PositiveSmallIntegerField(default=3)),
                ('start_score', models.PositiveSmallIntegerField(default=0)),
                ('target_score', models.PositiveSmallIntegerField(default=60)),
                ('weekly_hours', models.PositiveSmallIntegerField(default=4)),
                ('rationale', models.TextField(blank=True)),
                ('focus_topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_stages', to='academics.topic')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='diagnostics.roadmap')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roadmap_stages', to='academics.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('possible_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('question_count', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(default='low', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='diagnostics.diagnosticreport')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_results', to='academics.skill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('earned_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_flagged', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diagnostics.examattempt')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='academics.examquestion')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_selections', to='academics.questionoption')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('possible_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('level', models.CharField(max_length=30)),
                ('percentile', models.PositiveSmallIntegerField(default=0)),
                ('rank', models.CharField(blank=True, max_length=40)),
                ('potential', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='diagnostics.diagnosticreport')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_results', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('possible_points', models.DecimalField(decimal_places=2, max_digits=8)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('question_count', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(default='low', max_length=20)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_results', to='diagnostics.diagnosticreport')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_results', to='academics.topic')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('audience', models.CharField(choices=[('student', 'O‘quvchi'), ('teacher', 'O‘qituvchi'), ('parent', 'Ota-ona')], default='student', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('resource_url', models.URLField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_tasks', to='diagnostics.roadmapstage')),
            ],
            options={
                'ordering': ['week_number', 'audience', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='examassignment',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_student_assignment'),
        ),
        migrations.AddConstraint(
            model_name='roadmapstage',
            constraint=models.UniqueConstraint(fields=('roadmap', 'order'), name='unique_roadmap_stage_order'),
        ),
        migrations.AddConstraint(
            model_name='skillresult',
            constraint=models.UniqueConstraint(fields=('report', 'skill'), name='unique_report_skill_result'),
        ),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'exam_question'), name='unique_attempt_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='subjectresult',
            constraint=models.UniqueConstraint(fields=('report', 'subject'), name='unique_report_subject_result'),
        ),
        migrations.AddConstraint(
            model_name='topicresult',
            constraint=models.UniqueConstraint(fields=('report', 'topic'), name='unique_report_topic_result'),
        ),
    ]
