# Generated by Django 5.2.16 on 2026-07-20 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("diagnostics", "0001_initial"),
        ("profiling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examassignment",
            name="administered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administered_exam_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examassignment",
            name="delivery_mode",
            field=models.CharField(
                choices=[
                    ("self", "O‘quvchi mustaqil"),
                    ("administered", "Admin bilan"),
                ],
                default="self",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="started_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="started_exam_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examattempt",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_exam_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="admin_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="generation_context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="roadmap",
            name="primary_goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roadmaps",
                to="profiling.studentgoal",
            ),
        ),
        migrations.AlterField(
            model_name="examassignment",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_assignments",
                to="accounts.classroom",
            ),
        ),
    ]
