# Generated by Django 5.2.4 on 2026-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostics", "0005_assignment_batch_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentanswer",
            name="is_graded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="manual_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="text_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="examattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "Jarayonda"),
                    ("pending_review", "Ustoz tekshiruvi kutilmoqda"),
                    ("submitted", "Topshirildi"),
                    ("expired", "Vaqt tugadi"),
                ],
                db_index=True,
                default="in_progress",
                max_length=16,
            ),
        ),
    ]
