"""RBIS 2-4-sinflar matematika qabul diagnostikasi ma'lumotlari.

Savollar foydalanuvchi taqdim etgan uchta DOCX testdan ko'chirildi. 3-sinf
8-savoldagi "shar" so'zi ikki javobni teng ehtimolli qilgani uchun "kub" deb
aniqlashtirildi; rasm va javob variantlari o'zgartirilmadi.
"""

TOPIC_SPECS = {'numbers': {'code': 'M-NUM', 'title': 'Sonlar va hisoblash', 'healthy_threshold': 75, 'order': 1},
 'word-problems': {'code': 'M-WORD', 'title': 'Matnli masalalar', 'healthy_threshold': 70, 'order': 2},
 'algebra': {'code': 'M-ALG', 'title': 'Tenglama va algebraik fikrlash', 'healthy_threshold': 70, 'order': 3},
 'patterns': {'code': 'M-PAT', 'title': 'Qonuniyat va ketma-ketliklar', 'healthy_threshold': 70, 'order': 4},
 'geometry': {'code': 'M-GEO',
              'title': 'Geometriya va fazoviy fikrlash',
              'healthy_threshold': 70,
              'order': 5},
 'measurement': {'code': 'M-MEAS', 'title': 'O‘lchov birliklari', 'healthy_threshold': 75, 'order': 6},
 'data': {'code': 'M-DATA',
          'title': 'Ma’lumotlar, diagramma va ehtimollik',
          'healthy_threshold': 70,
          'order': 7},
 'logic': {'code': 'M-LOG', 'title': 'Mantiqiy masalalar', 'healthy_threshold': 70, 'order': 8}}

SKILL_SPECS = {'calculation': ('Hisoblash aniqligi', 1),
 'place-value': ('Son tuzilishi va xona qiymati', 2),
 'problem-solving': ('Masalani yechish', 3),
 'algebraic-reasoning': ('Algebraik fikrlash', 4),
 'pattern-recognition': ('Qonuniyatni aniqlash', 5),
 'geometric-reasoning': ('Geometrik-fazoviy tafakkur', 6),
 'measurement': ('O‘lchash va birliklarni almashtirish', 7),
 'data-interpretation': ('Diagramma va ma’lumotni talqin qilish', 8),
 'probability': ('Ehtimollikni tushunish', 9),
 'logical-reasoning': ('Mantiqiy xulosa chiqarish', 10)}

QUESTIONS_BY_GRADE = {2: [{'number': 1,
      'context': '',
      'prompt': 'Sardorda 225 ming so‘m pul bor. U sut sotib olishi uchun unga yana 35 ming so‘m kerak bo‘ladi. Sut '
                'qancha turadi?',
      'options': ['150 ming so‘m', '250 ming so‘m', '260 ming so‘m', '270 ming so‘m'],
      'answer': 'C',
      'explanation': '225 + 35 = 260 ming so‘m.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 2,
      'context': '',
      'prompt': 'Rasmdagi tartibga mos o‘lchov birliklarini toping.',
      'options': ['qarich, barmoq, quloch, oyoq, qadam',
                  'oyoq, barmoq, qarich, qadam, quloch',
                  'oyoq, barmoq, qarich, quloch, qadam',
                  'oyoq, qarich, barmoq, quloch, qadam'],
      'answer': 'B',
      'explanation': 'Rasmda oyoq, barmoq, qarich, qadam va quloch ketma-ket ko‘rsatilgan.',
      'topic': 'measurement',
      'skills': ['measurement', 'geometric-reasoning'],
      'difficulty': 'basic',
      'image': 'grade-2/q02.png'},
     {'number': 3,
      'context': '',
      'prompt': 'To‘g‘ri bajarilgan amalni toping.',
      'options': ['18 : 0 = 0', '2 · 3 = 5', '27 : 3 = 9', '412 : 4 = 13'],
      'answer': 'C',
      'explanation': '27 ni 3 ga bo‘lsak 9 hosil bo‘ladi.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 4,
      'context': '',
      'prompt': '3 ta olma sig‘adigan sumka 2 dollar turadi. Agar sumka narxlari olmalar sig‘imiga mos bo‘lsa, 10 '
                'dollarga sotib olingan sumkalarga nechta olma sig‘adi?',
      'options': ['5', '6', '15', '20'],
      'answer': 'C',
      'explanation': '10 dollar 5 ta sumka narxi; 5 · 3 = 15 ta olma.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 5,
      'context': '',
      'prompt': 'Samolyot manzilga yetishi uchun yana qancha masofani uchib o‘tishi kerak?',
      'options': ['1500 km', '600 km', '500 km', '300 km'],
      'answer': 'D',
      'explanation': '900 − 600 = 300 km.',
      'topic': 'measurement',
      'skills': ['measurement', 'problem-solving'],
      'difficulty': 'basic',
      'image': 'grade-2/q05.png'},
     {'number': 6,
      'context': '',
      'prompt': 'Rasmga asosan ikkita pomidorning vaznini toping.',
      'options': ['1', '2', '3', '4'],
      'answer': 'B',
      'explanation': '4 ta pomidor va 4 birlik 8 birlikka teng. Demak 4 ta pomidor 4 birlik, 2 tasi 2 birlik.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'problem-solving'],
      'difficulty': 'medium',
      'image': 'grade-2/q06.png'},
     {'number': 7,
      'context': '',
      'prompt': 'Tenglamaning ildizini toping: x + 12 + x = 22 + 18',
      'options': ['12', '14', '18', '22'],
      'answer': 'B',
      'explanation': '2x + 12 = 40, 2x = 28, x = 14.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 8,
      'context': '',
      'prompt': 'Miraziz boboning hozirgi yoshi 69 da. Uning nabirasi Mirjalol bobosidan 3 marta kichik. Mirjalolning '
                '3 yildan keyingi yoshini toping.',
      'options': ['23', '26', '28', '66'],
      'answer': 'B',
      'explanation': '69 : 3 = 23; 23 + 3 = 26.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 9,
      'context': '',
      'prompt': 'Birinchi sinfda 26 ta, ikkinchi sinfda undan 5 ta ko‘p o‘quvchi bor. Ikkala sinfda jami nechta '
                'o‘quvchi bor?',
      'options': ['52', '53', '57', '58'],
      'answer': 'C',
      'explanation': 'Ikkinchi sinfda 31 ta. 26 + 31 = 57.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 10,
      'context': '',
      'prompt': 'Shakllarda berilgan sonlar bog‘liqligidan foydalanib, so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['3', '7', '13', '17'],
      'answer': 'D',
      'explanation': 'Chap tomondagi sonlar yig‘indisidan o‘ng tomondagi sonlar yig‘indisi ayiriladi: (12 + 11) − (2 + '
                     '4) = 17.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-2/q10.png'},
     {'number': 11,
      'context': '',
      'prompt': 'Berilgan raqamlardan har birini bir martadan foydalanib, eng kichik olti xonali sonni yozing.',
      'options': ['510937', '739015', '013579', '103579'],
      'answer': 'D',
      'explanation': 'Olti xonali son 0 bilan boshlanmaydi. Eng kichik tartib 1,0,3,5,7,9: 103579.',
      'topic': 'numbers',
      'skills': ['place-value', 'logical-reasoning'],
      'difficulty': 'medium',
      'image': 'grade-2/q11.png'},
     {'number': 12,
      'context': '',
      'prompt': 'Hisoblashlar to‘g‘ri bajarilganda, so‘roq belgisi o‘rnida qaysi son bo‘ladi?',
      'options': ['2', '3', '4', '5'],
      'answer': 'B',
      'explanation': 'Pastki qatordan 8 − 4 = 4. O‘ng ustunda 13 − 9 = 4. Yuqorida 8 + 5 = 13. Chap ustunda 5 + ? = 8, '
                     'demak ? = 3.',
      'topic': 'logic',
      'skills': ['logical-reasoning', 'calculation'],
      'difficulty': 'high',
      'image': 'grade-2/q12.png'},
     {'number': 13,
      'context': '',
      'prompt': 'Yig‘indining qiymatini aniqlang.',
      'options': ['50', '60', '70', '80'],
      'answer': 'C',
      'explanation': 'Olma 14 + 17 = 31, nok 31 + 8 = 39. 31 + 39 = 70.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-2/q13.png'},
     {'number': 14,
      'context': '',
      'prompt': 'Hisoblang: (24 : 8) + (6 · 9) − (45 − 7)',
      'options': ['21', '23', '17', '19'],
      'answer': 'D',
      'explanation': '3 + 54 − 38 = 19.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 15,
      'context': '',
      'prompt': 'Berilgan qoidaga ko‘ra so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['18', '8', '16', '6'],
      'answer': 'B',
      'explanation': '(17 + 3) − (16 − 4) = 20 − 12 = 8.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-2/q15.png'},
     {'number': 16,
      'context': '',
      'prompt': 'Quyidagi yig‘indilardan qaysi biri eng katta?',
      'options': ['2 + 0 + 24 + 20 + 2 + 5', '20 + 24 + 2 + 0 + 2 + 5', '202 + 4 + 20 + 25', '20 + 242 + 0 + 2 + 5'],
      'answer': 'D',
      'explanation': 'Qiymatlar 53, 53, 251 va 269. Eng kattasi 269.',
      'topic': 'numbers',
      'skills': ['calculation', 'place-value'],
      'difficulty': 'medium',
      'image': None},
     {'number': 17,
      'context': '',
      'prompt': 'Tengliklar to‘g‘ri bo‘lsa, so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['10', '8', '12', '10'],
      'answer': 'B',
      'explanation': '36 − 20 = 16; 36 − 24 = 12; 20 − 16 = 4. Shunda 24 − 16 = 8.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'logical-reasoning'],
      'difficulty': 'high',
      'image': 'grade-2/q17.png'},
     {'number': 18,
      'context': '',
      'prompt': 'Bir o‘ram gul yasash uchun 9 dona atirgul kerak. Bir dona atirgul narxi 12 000 so‘m bo‘lsa, o‘ramning '
                'narxi necha so‘m?',
      'options': ['108 000 so‘m', '118 000 so‘m', '112 000 so‘m', '111 000 so‘m'],
      'answer': 'A',
      'explanation': '9 · 12 000 = 108 000 so‘m.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 19,
      'context': '',
      'prompt': 'Ayirmani hisoblang: 18 m 63 cm − 9 m 87 cm',
      'options': ['8 m 67 cm', '7 m 86 cm', '7 m 68 cm', '8 m 76 cm'],
      'answer': 'D',
      'explanation': '1 metrni 100 cm qilib olamiz: 17 m 163 cm − 9 m 87 cm = 8 m 76 cm.',
      'topic': 'measurement',
      'skills': ['measurement', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 20,
      'context': '',
      'prompt': 'Daftarning narxi 700 so‘m. Qalam daftardan ikki marta arzon. 3 ta daftar va 1 ta qalam birgalikda '
                'necha so‘m bo‘ladi?',
      'options': ['1050 so‘m', '2100 so‘m', '1750 so‘m', '2450 so‘m'],
      'answer': 'D',
      'explanation': 'Qalam 350 so‘m. 3 · 700 + 350 = 2450 so‘m.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None}],
 3: [{'number': 1,
      'context': '',
      'prompt': 'Har bir qo‘ng‘izning 6 ta oyog‘i bor. Rasmdagi qo‘ng‘izlarning jami oyoqlari soni qaysi variantda '
                'to‘g‘ri ko‘rsatilgan?',
      'options': ['3 + 3 + 3', '6 + 3', '6 − 3', '6 + 6 + 6'],
      'answer': 'D',
      'explanation': '3 ta qo‘ng‘izning har biri 6 oyoqli: 6 + 6 + 6 = 18.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': 'grade-3/q01.png'},
     {'number': 2,
      'context': '',
      'prompt': 'Besh yuz yigirma sakkiz ming besh yuz so‘m pul miqdori qanday yoziladi?',
      'options': ['528555', '588050', '528500', '528550'],
      'answer': 'C',
      'explanation': 'Besh yuz yigirma sakkiz ming besh yuz = 528 500.',
      'topic': 'numbers',
      'skills': ['place-value'],
      'difficulty': 'basic',
      'image': None},
     {'number': 3,
      'context': '',
      'prompt': 'N soni 89 va 45 ning ayirmasiga teng. N ni toping.',
      'options': ['34', '44', '54', '64'],
      'answer': 'B',
      'explanation': '89 − 45 = 44.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 4,
      'context': '',
      'prompt': 'Rasmga e’tibor qiling. Uchburchak qaysi katakda turibdi?',
      'options': ['D2', 'D1', 'B5', 'C3'],
      'answer': 'A',
      'explanation': 'Uchburchak D ustun va 2-qator kesishgan katakda.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'data-interpretation'],
      'difficulty': 'basic',
      'image': 'grade-3/q04.png'},
     {'number': 5,
      'context': '',
      'prompt': '1429, 2287 va 1534 sonlarining yig‘indisini toping.',
      'options': ['3026', '5250', '5313', '5413'],
      'answer': 'B',
      'explanation': '1429 + 2287 + 1534 = 5250.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 6,
      'context': '',
      'prompt': 'Qutida 6 ta qizil, 10 ta ko‘k va 4 ta sariq shar bor. Qutidan qaysi rangdagi shar chiqishi imkonsiz?',
      'options': ['qizil', 'ko‘k', 'oq', 'sariq'],
      'answer': 'C',
      'explanation': 'Qutida oq shar yo‘q.',
      'topic': 'data',
      'skills': ['probability', 'logical-reasoning'],
      'difficulty': 'basic',
      'image': None},
     {'number': 7,
      'context': '',
      'prompt': 'Har birida 5 ta ruchka bo‘lgan 6 ta idishdagi ruchkalar soni, har birida nechta ruchka bo‘lgan 3 ta '
                'idishdagi ruchkalar soniga teng?',
      'options': ['10', '6', '5', '3'],
      'answer': 'A',
      'explanation': '6 · 5 = 30; 30 : 3 = 10.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 8,
      'context': '',
      'prompt': 'Charos qutiga qaramasdan kubni olmoqchi. Qaysi qutidan olsa kub chiqishi ehtimoli eng katta?',
      'options': ['A quti', 'B quti', 'C quti', 'D quti'],
      'answer': 'A',
      'explanation': 'A qutida 6 shakldan 3 tasi kub, ya’ni ehtimol 1/2. B va C da kub ulushi 1/3, D da 1/6.',
      'topic': 'data',
      'skills': ['probability', 'data-interpretation'],
      'difficulty': 'medium',
      'image': 'grade-3/q08.png'},
     {'number': 9,
      'context': '',
      'prompt': '22 + 19 bilan bir xil qiymatga ega bo‘lgan 20 + ? yig‘indisidagi sonni toping.',
      'options': ['22', '19', '20', '21'],
      'answer': 'D',
      'explanation': '22 + 19 = 41; 20 + 21 = 41.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 10,
      'context': '',
      'prompt': 'Rahim yo‘l ko‘rsatkichi yonidan yo‘lga chiqdi. U avval daryoga bordi, so‘ng orqaga qaytib kioskga '
                'bordi. U jami necha kilometr yo‘l bosdi?',
      'options': ['7 km', '10 km', '12 km', '14 km'],
      'answer': 'C',
      'explanation': 'Daryogacha 5 km, qaytib ko‘rsatkichgacha 5 km va kioskgacha 2 km: 12 km.',
      'topic': 'measurement',
      'skills': ['measurement', 'problem-solving'],
      'difficulty': 'medium',
      'image': 'grade-3/q10.png'},
     {'number': 11,
      'context': '',
      'prompt': 'Lobar 34 ta pirogni qutilarga solmoqda. Har bir qutiga 5 ta pirog sig‘adi. Hamma pirog uchun jami '
                'nechta quti kerak?',
      'options': ['5', '6', '7', '8'],
      'answer': 'C',
      'explanation': '34 : 5 = 6 qoldiq 4, shuning uchun yana bitta quti kerak: 7.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 12,
      'context': '',
      'prompt': 'Qaysi son o‘nlar xonasigacha yaxlitlanganda 90 ga teng bo‘ladi?',
      'options': ['69', '72', '76', '85'],
      'answer': 'D',
      'explanation': '85 soni o‘nlikkacha yaxlitlanganda 90 bo‘ladi.',
      'topic': 'numbers',
      'skills': ['place-value', 'calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 13,
      'context': '',
      'prompt': 'Sonlar devoridagi qonuniyat bo‘yicha X + Y ni toping.',
      'options': ['86', '115', '117', '118'],
      'answer': 'B',
      'explanation': 'Har bir yuqori g‘isht pastdagi ikki g‘isht yig‘indisi. X = 5, Y = 110, shuning uchun X + Y = '
                     '115.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'high',
      'image': 'grade-3/q13.png'},
     {'number': 14,
      'context': '',
      'prompt': 'Avstraliya xaritasining vertikal o‘qqa nisbatan simmetrik ko‘rinishini tanlang.',
      'options': ['A variant', 'B variant', 'C variant', 'D variant'],
      'answer': 'D',
      'explanation': 'Vertikal akslantirishda xaritaning chap va o‘ng tomonlari almashadi, yuqori-past holati '
                     'saqlanadi. Buni D variant ko‘rsatadi.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning'],
      'difficulty': 'medium',
      'image': 'grade-3/q14.png'},
     {'number': 15,
      'context': '',
      'prompt': 'Har bir juftlikdagi sonlar bir xil qoida asosida bog‘langan. Yetishmayotgan sonni toping: [12, 5], '
                '[18, 8], [14, 6], [10, ?]',
      'options': ['0', '2', '3', '4'],
      'answer': 'D',
      'explanation': 'Ikkinchi son birinchi sonning yarmidan 1 ayirilgan: 10 : 2 − 1 = 4.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 16,
      'context': '',
      'prompt': 'Eni 10 cm, bo‘yi 8 cm bo‘lgan to‘g‘ri to‘rtburchakning perimetri son jihatdan kvadratning yuziga '
                'teng. Kvadrat tomonini toping.',
      'options': ['9 cm', '18 cm', '6 cm', '36 cm'],
      'answer': 'C',
      'explanation': 'To‘g‘ri to‘rtburchak perimetri 2 · (10 + 8) = 36. Yuzasi 36 bo‘lgan kvadrat tomoni 6 cm.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 17,
      'context': '',
      'prompt': '859 ga 3740 va 870 sonlari ayirmasini qo‘shing.',
      'options': ['2011', '5469', '3615', '3729'],
      'answer': 'D',
      'explanation': '3740 − 870 = 2870; 2870 + 859 = 3729.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 18,
      'context': '',
      'prompt': 'Diyorbek 22 yosh. Javohir Kamrondan 9 yosh katta va Azizbekdan 6 yosh katta. Kamron Diyorbekdan 8 '
                'yosh katta. Azizbek necha yoshda?',
      'options': ['30', '33', '36', '39'],
      'answer': 'B',
      'explanation': 'Kamron 30, Javohir 39, Azizbek esa 39 − 6 = 33 yosh.',
      'topic': 'word-problems',
      'skills': ['problem-solving', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 19,
      'context': '',
      'prompt': 'Ketma-ket kelgan 3 ta sonning ko‘paytmasi quyidagilarning qaysi biriga bo‘linmasligi mumkin?',
      'options': ['6', '2', '9', '3'],
      'answer': 'C',
      'explanation': 'Uch ketma-ket son ko‘paytmasi har doim 2, 3 va 6 ga bo‘linadi, lekin 9 ga bo‘linmasligi mumkin.',
      'topic': 'numbers',
      'skills': ['logical-reasoning', 'calculation'],
      'difficulty': 'high',
      'image': None},
     {'number': 20,
      'context': '',
      'prompt': 'Qaysi son 12 ga bo‘linmaydi?',
      'options': ['60', '28', '48', '72'],
      'answer': 'B',
      'explanation': '28 soni 12 ga qoldiqsiz bo‘linmaydi.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 21,
      'context': '',
      'prompt': 'To‘g‘ri to‘rtburchak perimetri 124 ga teng. Uning turli tomonlari yig‘indisini toping.',
      'options': ['31', '62', '248', '72'],
      'answer': 'B',
      'explanation': '2(a + b) = 124, demak a + b = 62.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'algebraic-reasoning'],
      'difficulty': 'medium',
      'image': None},
     {'number': 22,
      'context': '',
      'prompt': 'Rasmdagi katta uchburchak perimetrini toping.',
      'options': ['45 cm', '36 cm', '14 cm', '42 cm'],
      'answer': 'D',
      'explanation': 'Belgilangan barcha kichik kesmalar teng va bittasi 7 cm. Katta uchburchakning har tomoni 14 cm, '
                     'perimetri 42 cm.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'measurement'],
      'difficulty': 'medium',
      'image': 'grade-3/q22.png'},
     {'number': 23,
      'context': '',
      'prompt': 'O‘lchamlari 24 m, 30 m va 450 dm bo‘lgan to‘g‘ri burchakli parallelepiped hajmini toping.',
      'options': ['32400 m³', '33400 m³', '31400 m³', '22400 m³'],
      'answer': 'A',
      'explanation': '450 dm = 45 m. Hajm 24 · 30 · 45 = 32400 m³.',
      'topic': 'measurement',
      'skills': ['measurement', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 24,
      'context': '',
      'prompt': 'Agar 6 · 30 = a va 6 · 4 = b bo‘lsa, 6 · 26 nimaga teng?',
      'options': ['a + b', 'a − b', 'a + 24', 'a · b'],
      'answer': 'B',
      'explanation': '6 · 26 = 6 · (30 − 4) = a − b.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 25,
      'context': '',
      'prompt': 'Rasmdagi shakllar qiymatlaridan foydalanib, so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['30', '35', '40', '42'],
      'answer': 'A',
      'explanation': 'Tenglamalardan kvadrat 14, uchburchak 11, yulduz 19, sakkizburchak 19 chiqadi. Yulduz + '
                     'uchburchak = 30.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'logical-reasoning'],
      'difficulty': 'high',
      'image': 'grade-3/q25.png'},
     {'number': 26,
      'context': '',
      'prompt': 'Kurant soati soat mili nechani ko‘rsatsa, shuncha marta bong uradi. Bir sutkada necha marta bong '
                'uradi?',
      'options': ['156', '78', '48', '72'],
      'answer': 'A',
      'explanation': '12 soatda 1 + 2 + ... + 12 = 78 marta. Bir sutkada 2 · 78 = 156.',
      'topic': 'word-problems',
      'skills': ['calculation', 'pattern-recognition'],
      'difficulty': 'medium',
      'image': None},
     {'number': 27,
      'context': '',
      'prompt': 'Hisoblang: (31 · 9 − 754 : 29) · (1323 : 27 − 31)',
      'options': ['4544', '4454', '4554', '5454'],
      'answer': 'C',
      'explanation': '31 · 9 = 279, 754 : 29 = 26, 1323 : 27 = 49. (279 − 26) · (49 − 31) = 253 · 18 = 4554.',
      'topic': 'numbers',
      'skills': ['calculation'],
      'difficulty': 'high',
      'image': None},
     {'number': 28,
      'context': '',
      'prompt': '3, 4, 1, 5, 7, 10, 8, 9 sonlar qatorining medianasini toping.',
      'options': ['10', '5', '6', '5,5'],
      'answer': 'C',
      'explanation': 'Tartiblangan qator: 1,3,4,5,7,8,9,10. Median (5 + 7) : 2 = 6.',
      'topic': 'data',
      'skills': ['data-interpretation', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 29,
      'context': '',
      'prompt': 'Berilgan amallar qoidasi bo‘yicha ifodaning qiymatini toping.',
      'options': ['100', '10', '78300', '0'],
      'answer': 'D',
      'explanation': '2 □ 3 = 3·2 − 2·3 = 0. Birinchi ko‘paytuvchi 0 bo‘lgani uchun butun ifoda 0.',
      'topic': 'logic',
      'skills': ['logical-reasoning', 'algebraic-reasoning'],
      'difficulty': 'high',
      'image': 'grade-3/q29.png'},
     {'number': 30,
      'context': '',
      'prompt': 'Kodlar mosligini aniqlab, CAM so‘zining kodini toping.',
      'options': ['316', '317', '318', '718'],
      'answer': 'A',
      'explanation': 'Moslashtirishdan C=3, A=1, M=6 kelib chiqadi. CAM = 316.',
      'topic': 'logic',
      'skills': ['logical-reasoning', 'pattern-recognition'],
      'difficulty': 'high',
      'image': 'grade-3/q30.png'}],
 4: [{'number': 1,
      'context': '',
      'prompt': '▲ katta songa teng. ▲ sonini 777 ga bo‘lganda bo‘linma 888 va qoldiq 66 bo‘lsa, ▲ ni qaysi amal '
                'beradi?',
      'options': ['(777 + 66) × 888', '(888 + 66) × 777', '(888 − 66) × 777', '888 × 777 + 66', '888 × 777 − 66'],
      'answer': 'D',
      'explanation': 'Bo‘linuvchi = bo‘luvchi × bo‘linma + qoldiq: 777 × 888 + 66.',
      'topic': 'numbers',
      'skills': ['calculation', 'algebraic-reasoning'],
      'difficulty': 'medium',
      'image': None},
     {'number': 2,
      'context': '',
      'prompt': 'Koordinatalari (10; 5) va (10; 3) bo‘lgan nuqtalarni tutashtiruvchi kesma uzunligini toping.',
      'options': ['2', '4', '8', '10', '12'],
      'answer': 'A',
      'explanation': 'x koordinatalar teng, y koordinatalar farqi 5 − 3 = 2.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 3,
      'context': '',
      'prompt': 'Ketma-ketlikdagi tushirib qoldirilgan sonlar yig‘indisini toping: 15; 23; 31; ...; ...; 55; 63',
      'options': ['16', '39', '43', '78', '86'],
      'answer': 'E',
      'explanation': 'Ketma-ketlik 8 tadan ortadi: 39 va 47. Ularning yig‘indisi 86.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 4,
      'context': '',
      'prompt': 'Diagrammaga ko‘ra 12 yoshdan yoshroq bolalar sonini toping.',
      'options': ['20', '25', '55', '100', '120'],
      'answer': 'D',
      'explanation': '9, 10 va 11 yoshdagilar: 15 + 40 + 45 = 100.',
      'topic': 'data',
      'skills': ['data-interpretation', 'calculation'],
      'difficulty': 'basic',
      'image': 'grade-4/q04.png'},
     {'number': 5,
      'context': '',
      'prompt': 'Umidda 7 kilogramm un bor. Har bir tort uchun 400 gramm un ishlatib, imkon qadar ko‘p tort '
                'tayyorlasa, qancha un qoladi?',
      'options': ['17 gramm', '20 gramm', '57 gramm', '200 gramm', '300 gramm'],
      'answer': 'D',
      'explanation': '7000 : 400 = 17 qoldiq 200. 200 gramm un qoladi.',
      'topic': 'measurement',
      'skills': ['measurement', 'calculation', 'problem-solving'],
      'difficulty': 'medium',
      'image': None},
     {'number': 6,
      'context': '',
      'prompt': '(P − 15) × 43 = 946 tenglamadan P ni topish uchun qaysi amal ishlatiladi?',
      'options': ['P = (946 − 15) × 43',
                  'P = (946 + 15) : 43',
                  'P = 946 × 43 − 15',
                  'P = 946 : 43 − 15',
                  'P = 946 : 43 + 15'],
      'answer': 'E',
      'explanation': 'Avval 946 ni 43 ga bo‘lamiz, keyin 15 qo‘shamiz: P = 946 : 43 + 15.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 7,
      'context': '',
      'prompt': 'Tenglamani yeching: (17 + x · x) · 6 = 18 · 71',
      'options': ['16', '98', '49', '14', '24'],
      'answer': 'D',
      'explanation': '18 · 71 = 1278; 1278 : 6 = 213; x² = 196; x = 14.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'high',
      'image': None},
     {'number': 8,
      'context': '',
      'prompt': 'A = 310 + 311 + ... + 320 va B = 110 + 111 + ... + 120 bo‘lsa, A − B ni toping.',
      'options': ['2220', '2200', '2000', '2020', '3202'],
      'answer': 'B',
      'explanation': 'Har bir mos hadning farqi 200 va 11 ta had bor: 11 · 200 = 2200.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 9,
      'context': '',
      'prompt': 'Fabrikada har 25 ta ishlab chiqaruvchi ishchiga 2 tadan nazoratchi bor. 300 ta ishlab chiqaruvchi '
                'ishchi uchun nechta nazoratchi kerak?',
      'options': ['6', '12', '24', '50', '150'],
      'answer': 'C',
      'explanation': '300 : 25 = 12 guruh; 12 · 2 = 24 nazoratchi.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'basic',
      'image': None},
     {'number': 10,
      'context': '',
      'prompt': '20 cm uzunlikdagi AB kesma 10 ta teng bo‘lakka bo‘lingan. CB − CD uzunligi AB kesmaning qanday '
                'qismini tashkil qiladi?',
      'options': ['3/20', '2/10', '5/20', '6/10', '6/20'],
      'answer': 'E',
      'explanation': 'CB 6 bo‘lak, CD 3 bo‘lak; farq 3 bo‘lak = 3/10 = 6/20.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-4/q10.png'},
     {'number': 11,
      'context': '',
      'prompt': 'Kvadrat va teng tomonli uchburchak perimetri bir xil. Uchburchak tomoni 36 cm bo‘lsa, kvadrat '
                'tomonini toping.',
      'options': ['12 cm', '27 cm', '36 cm', '48 cm', '144 cm'],
      'answer': 'B',
      'explanation': 'Uchburchak perimetri 3 · 36 = 108 cm. Kvadrat tomoni 108 : 4 = 27 cm.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'calculation'],
      'difficulty': 'basic',
      'image': None},
     {'number': 12,
      'context': '',
      'prompt': '▲ : 12 = 144 bo‘lsa, ▲ : 36 ni toping.',
      'options': ['4', '12', '48', '108', '432'],
      'answer': 'C',
      'explanation': '▲ = 144 · 12 = 1728; 1728 : 36 = 48.',
      'topic': 'numbers',
      'skills': ['calculation', 'algebraic-reasoning'],
      'difficulty': 'medium',
      'image': None},
     {'number': 13,
      'context': '',
      'prompt': 'Kuboidning barcha qirralari uzunliklari yig‘indisini toping.',
      'options': ['24 cm', '34 cm', '36 cm', '48 cm', '60 cm'],
      'answer': 'D',
      'explanation': 'Kuboid qirralari yig‘indisi 4 · (4 + 3 + 5) = 48 cm.',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'measurement'],
      'difficulty': 'basic',
      'image': 'grade-4/q13.png'},
     {'number': 14,
      'context': '',
      'prompt': 'Piyoz 850 so‘m. Piyoz pomidordan 6 marta arzon; sabzi pomidordan 2500 so‘m arzon; 5 kg sabzi 1 kg '
                'uzum narxiga; uzum olmadan 2 marta qimmat; 4 kg piyoz va 3 kg pomidor 1 kg banan narxiga teng. 1 kg '
                'olma va 1 kg bananning jami narxini toping.',
      'options': ['27 500 so‘m', '26 400 so‘m', '27 800 so‘m', '25 200 so‘m', '28 000 so‘m'],
      'answer': 'D',
      'explanation': 'Pomidor 5100, sabzi 2600, uzum 13000, olma 6500, banan 18700. Jami 25200 so‘m.',
      'topic': 'word-problems',
      'skills': ['problem-solving', 'calculation'],
      'difficulty': 'high',
      'image': None},
     {'number': 15,
      'context': '',
      'prompt': 'Javlon 200 daqiqada 60 000 metr masofa bosib o‘tadi. Uning tezligini soatiga kilometrlarda toping.',
      'options': ['3 km/soat', '18 km/soat', '30 km/soat', '180 km/soat', '300 km/soat'],
      'answer': 'B',
      'explanation': '60 000 m = 60 km; 200 daqiqa = 10/3 soat. 60 : (10/3) = 18 km/soat.',
      'topic': 'measurement',
      'skills': ['measurement', 'calculation', 'problem-solving'],
      'difficulty': 'medium',
      'image': None},
     {'number': 16,
      'context': '',
      'prompt': 'Shokolad plitkasi bir xil bo‘laklardan iborat. Sardor 6 bo‘lakni oyisiga va 7 bo‘lakni otasiga berdi. '
                'Rasmga ko‘ra o‘ziga nechta bo‘lak qoldi?',
      'options': ['36 ta', '35 ta', '30 ta', '29 ta', '28 ta'],
      'answer': 'D',
      'explanation': 'Plitkada 42 bo‘lak bor. 42 − 6 − 7 = 29.',
      'topic': 'geometry',
      'skills': ['data-interpretation', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-4/q16.png'},
     {'number': 17,
      'context': '',
      'prompt': 'Jamoa boshida 10 ochkoga ega edi. G‘alaba uchun 3 ochko qo‘shildi, mag‘lubiyat uchun 1 ochko '
                'ayirildi. Jamoa 4 marta yutqazib, yakunda 24 ochkoga ega bo‘lsa, necha marta g‘alaba qilgan?',
      'options': ['6 ta', '7 ta', '8 ta', '10 ta', '18 ta'],
      'answer': 'A',
      'explanation': '10 − 4 + 3x = 24; 3x = 18; x = 6.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'problem-solving'],
      'difficulty': 'medium',
      'image': None},
     {'number': 18,
      'context': '',
      'prompt': 'Mulohazalarning to‘g‘ri yoki noto‘g‘riligini aniqlang: I) avval qavs ichidagi amallar bajariladi; II) '
                'vaqtni topish uchun masofa tezlikka ko‘paytiriladi; III) faqat ikki tomoni teng bo‘lmagan uchburchak '
                'albatta turli tomonli bo‘ladi.',
      'options': ['I — to‘g‘ri, II — noto‘g‘ri, III — to‘g‘ri',
                  'I — noto‘g‘ri, II — to‘g‘ri, III — noto‘g‘ri',
                  'I — noto‘g‘ri, II — noto‘g‘ri, III — to‘g‘ri',
                  'I — to‘g‘ri, II — noto‘g‘ri, III — noto‘g‘ri'],
      'answer': 'D',
      'explanation': 'I to‘g‘ri. Vaqt = masofa : tezlik, shuning uchun II noto‘g‘ri. Ikki tomoni teng bo‘lmagan '
                     'uchburchak teng yonli bo‘lishi ham mumkin, III noto‘g‘ri.',
      'topic': 'logic',
      'skills': ['logical-reasoning'],
      'difficulty': 'medium',
      'image': None},
     {'number': 19,
      'context': '',
      'prompt': 'Sinfdagi o‘quvchilar teng qatorlarga o‘tirgan. Suxrob oldida 2 qator, orqasida 1 qator bor. Uning '
                'qatorida chapida 3 va o‘ngida 5 o‘quvchi bor. Sinfda jami nechta o‘quvchi bor?',
      'options': ['27 ta', '33 ta', '36 ta', '24 ta', '28 ta'],
      'answer': 'C',
      'explanation': '4 ta qator bor. Har qatorda 3 + 1 + 5 = 9 o‘quvchi. 4 · 9 = 36.',
      'topic': 'word-problems',
      'skills': ['problem-solving', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 20,
      'context': '',
      'prompt': 'Qopdagi tangalar jami 14 000 so‘m. Faqat 200 va 500 so‘mlik tangalar bor. 200 so‘mlik tangalar aniq '
                '25 ta bo‘lsa, 500 so‘mlik tangalar nechta?',
      'options': ['3', '18', '20', '28', '45'],
      'answer': 'B',
      'explanation': '25 · 200 = 5000; 14000 − 5000 = 9000; 9000 : 500 = 18.',
      'topic': 'word-problems',
      'skills': ['calculation', 'problem-solving'],
      'difficulty': 'medium',
      'image': None},
     {'number': 21,
      'context': '',
      'prompt': 'Rasmda A, B va C idishlar suv bilan to‘ldirilgan. A idishdagi suv B idishdagidan 4 marta ko‘p bo‘lsa, '
                'A idishdagi suv C idishdagidan necha litr ko‘p?',
      'options': ['4', '7', '6', '5', '8'],
      'answer': 'B',
      'explanation': 'A + B = 15 va A = 4B, demak B = 3, A = 12. A + B + C = 20 dan C = 5. A − C = 7.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'problem-solving'],
      'difficulty': 'high',
      'image': 'grade-4/q21.png'},
     {'number': 22,
      'context': '',
      'prompt': 'Har bir kichik katak yuzasi 1 cm². Jadvalning bo‘yalgan yuzasini toping.',
      'options': ['30 cm²', '32 cm²', '44 cm²', '60 cm²', '64 cm²'],
      'answer': 'A',
      'explanation': 'Bo‘yalgan qism 8 × 8 ichki kvadrat yuzasidan oq to‘rtburchak yuzasi ayiriladi: 64 − 34 = 30 cm².',
      'topic': 'geometry',
      'skills': ['geometric-reasoning', 'data-interpretation'],
      'difficulty': 'high',
      'image': 'grade-4/q22.png'},
     {'number': 23,
      'context': '',
      'prompt': 'Qutida faqat sariq va yashil konfetlar bor. Konfetlarning 1/4 qismi sariq, 36 tasi yashil. Jami '
                'konfetlar nechta?',
      'options': ['45', '48', '72', '108', '144'],
      'answer': 'B',
      'explanation': 'Yashil konfetlar jami sonning 3/4 qismi. 36 : 3 · 4 = 48.',
      'topic': 'word-problems',
      'skills': ['problem-solving', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 24,
      'context': '',
      'prompt': 'Ikki butun sonning ayirmasi 8 va yig‘indisi 30. Ularning ko‘paytmasini toping.',
      'options': ['176', '209', '216', '345', '660'],
      'answer': 'B',
      'explanation': 'x − y = 8, x + y = 30. x = 19, y = 11, ko‘paytma 209.',
      'topic': 'algebra',
      'skills': ['algebraic-reasoning', 'calculation'],
      'difficulty': 'medium',
      'image': None},
     {'number': 25,
      'context': '',
      'prompt': 'Ketma-ketlik qonuniyatini aniqlab, so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['67', '74', '66', '71', '39'],
      'answer': 'A',
      'explanation': 'Har bir keyingi son oldingi songa uning raqamlari yig‘indisini qo‘shish orqali olinadi: 56 + 5 + '
                     '6 = 67.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-4/q25.png'},
     {'number': 26,
      'context': '',
      'prompt': 'Hilola ketma-ket butun sonlarni yozdi. Oxirgi son 114, jami 57 ta raqam yozilgan. Birinchi sonni '
                'toping.',
      'options': ['88', '92', '93', '94', '95'],
      'answer': 'D',
      'explanation': '94–99 oralig‘ida 6 ta ikki xonali son: 12 raqam. 100–114 oralig‘ida 15 ta uch xonali son: 45 '
                     'raqam. Jami 57.',
      'topic': 'numbers',
      'skills': ['place-value', 'logical-reasoning'],
      'difficulty': 'high',
      'image': None},
     {'number': 27,
      'context': '',
      'prompt': '75 o‘quvchidan 25 nafari kamida 84 ball olgan. Barcha 75 o‘quvchining mumkin bo‘lgan eng kichik '
                'o‘rtacha bali qancha?',
      'options': ['40', '50', '28', '35', '42'],
      'answer': 'C',
      'explanation': 'Eng kichik holatda 25 o‘quvchi 84, qolgan 50 o‘quvchi 0 oladi. O‘rtacha (25 · 84) : 75 = 28.',
      'topic': 'data',
      'skills': ['data-interpretation', 'logical-reasoning', 'calculation'],
      'difficulty': 'high',
      'image': None},
     {'number': 28,
      'context': '',
      'prompt': 'Grafikka ko‘ra poyga boshlanganidan aniq 4 sekund o‘tganda Salim va Jamshid orasidagi masofani '
                'toping.',
      'options': ['1 metr', '2 metr', '3 metr', '6 metr', '8 metr'],
      'answer': 'D',
      'explanation': '4 sekundda biri 14 metr, ikkinchisi 8 metr bosgan. Farq 6 metr.',
      'topic': 'data',
      'skills': ['data-interpretation', 'calculation'],
      'difficulty': 'medium',
      'image': 'grade-4/q28.png'},
     {'number': 29,
      'context': '',
      'prompt': 'Jadvaldagi qonuniyat bo‘yicha so‘roq belgisi o‘rnidagi sonni toping.',
      'options': ['101', '95', '100', '90', '80'],
      'answer': 'E',
      'explanation': 'O‘rta son chap va o‘ng sonlarning o‘rtacha qiymatini o‘nlikda ifodalaydi: (5 + 11) : 2 = 8, '
                     'demak 80.',
      'topic': 'patterns',
      'skills': ['pattern-recognition', 'logical-reasoning'],
      'difficulty': 'high',
      'image': 'grade-4/q29.png'},
     {'number': 30,
      'context': '',
      'prompt': 'Fotima, Komila, Sardor va Ahmadning kitoblari tarix, fizika, matematika va informatika. Fotimada '
                'informatika ham tarix kitobi ham yo‘q. Matematika kitobi egasi Ahmad va fizika kitobi egasi bilan, '
                'Sardor esa tarix kitobi egasi va Komila bilan yonma-yon turgan. Kitoblarni aniqlang.',
      'options': ['Fotima — fizika, Komila — matematika, Sardor — tarix, Ahmad — informatika',
                  'Fotima — matematika, Komila — tarix, Sardor — fizika, Ahmad — informatika',
                  'Fotima — fizika, Komila — matematika, Sardor — informatika, Ahmad — tarix',
                  'Fotima — matematika, Komila — fizika, Sardor — informatika, Ahmad — tarix'],
      'answer': 'D',
      'explanation': 'Shartlarni aylana bo‘ylab joylashtirganda Ahmad–Fotima–Komila–Sardor tartibi mos keladi. Shunda '
                     'Fotimada matematika, Komilada fizika, Sardorda informatika, Ahmadda tarix kitobi bor.',
      'topic': 'logic',
      'skills': ['logical-reasoning'],
      'difficulty': 'high',
      'image': None}]}

DURATION_MINUTES = {2: 45, 3: 60, 4: 60}
