# Generated by Django 5.2.16 on 2026-07-20 08:55

import apps.profiling.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("direction", "Ta’lim yo‘nalishi"),
                            ("subject_level", "Fan darajasi"),
                            ("support", "Qo‘llab-quvvatlash"),
                            ("motivation", "Motivatsiya"),
                            ("learning_style", "O‘rganish usuli"),
                            ("special", "Maxsus holat"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("subject_slug", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#071b3a", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["kind", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_code",
                    models.CharField(
                        default=apps.profiling.models.generate_admission_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("school_name", models.CharField(blank=True, max_length=200)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=120)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("weekly_study_hours", models.PositiveSmallIntegerField(default=5)),
                (
                    "learning_style",
                    models.CharField(
                        choices=[
                            ("visual", "Vizual"),
                            ("practical", "Amaliy"),
                            ("reading", "O‘qish orqali"),
                            ("mixed", "Aralash"),
                            ("unknown", "Aniqlanmagan"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("internet_access", models.BooleanField(default=True)),
                ("device_access", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("interview_draft", "Suhbat jarayonida"),
                            ("interview_completed", "Suhbat yakunlandi"),
                            ("test_recommended", "Test tavsiya qilindi"),
                            ("test_assigned", "Test biriktirildi"),
                            ("diagnosed", "Diagnostika yakunlandi"),
                            ("roadmap_draft", "Roadmap tayyorlanmoqda"),
                            ("active", "Faol o‘quvchi"),
                            ("paused", "Vaqtincha to‘xtatilgan"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_admin",
                    models.ForeignKey(
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_student_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_teacher",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "teacher"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_student_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Jarayonda"), ("completed", "Yakunlangan")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("interests", models.TextField(blank=True)),
                ("main_problem", models.TextField(blank=True)),
                ("motivation_level", models.CharField(blank=True, max_length=30)),
                ("independence_level", models.CharField(blank=True, max_length=30)),
                ("parent_support_level", models.CharField(blank=True, max_length=30)),
                ("admin_summary", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("next_step", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conducted_student_interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="profiling.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("presidential_school", "Prezident maktabi"),
                            ("ielts", "IELTS"),
                            ("sat", "SAT"),
                            ("university", "Universitet"),
                            ("olympiad", "Olimpiada"),
                            ("school_improvement", "Maktab natijasi"),
                            ("general", "Umumiy rivojlanish"),
                            ("other", "Boshqa"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("current_value", models.CharField(blank=True, max_length=100)),
                ("target_value", models.CharField(blank=True, max_length=100)),
                (
                    "target_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="profiling.studentprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-is_primary", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuardianContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=180)),
                ("relationship", models.CharField(default="Ota-ona", max_length=50)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("workplace", models.CharField(blank=True, max_length=180)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_contacts",
                        to="profiling.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_key", models.CharField(max_length=100)),
                ("question_text", models.CharField(max_length=300)),
                ("answer_text", models.TextField(blank=True)),
                ("score", models.SmallIntegerField(blank=True, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="profiling.studentinterview",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("interview", "question_key"),
                        name="unique_interview_question",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Admin tomonidan"),
                            ("interview", "Suhbat natijasida"),
                            ("diagnostic", "Diagnostika natijasida"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="profiling.category",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="profiling.studentprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "category"),
                        name="unique_student_profile_category",
                    )
                ],
            },
        ),
    ]
