# Generated by Django 5.2.4 on 2026-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_classrooms',
            field=models.ManyToManyField(blank=True, help_text='Test qaysi sinflar uchun tayyorlanganini belgilaydi.', related_name='available_exams', to='accounts.classroom'),
        ),
    ]
