# Generated by Django 5.2.16 on 2026-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0003_exam_target_classrooms"),
        ("profiling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("admission", "Qabul diagnostikasi"),
                    ("presidential_school", "Prezident maktabi"),
                    ("ielts", "IELTS"),
                    ("sat", "SAT"),
                    ("olympiad", "Olimpiada"),
                    ("general", "Umumiy diagnostika"),
                ],
                db_index=True,
                default="general",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="recommended_categories",
            field=models.ManyToManyField(
                blank=True, related_name="recommended_exams", to="profiling.category"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="max_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="min_grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
