# Generated by Django 5.2.4 on 2026-08-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academics", "0006_rbis_subject_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="accepted_text_answers",
            field=models.TextField(
                blank=True,
                help_text="Yozma savol uchun qabul qilinadigan javoblar. Har bir muqobil javobni yangi qatorda yozing.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_tolerance",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Sonli javoblar uchun ruxsat etilgan farq. Masalan: 0.01",
                max_digits=10,
            ),
        ),
    ]
